when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
app_registration:
    path: /registration
    controller: App\Controller\RegistrationController::register
